/* Baza pytań — Świadectwo Kwalifikacji Pilota Paralotni.
   Pytania i warianty odpowiedzi pochodzą od użytkownika.
   Pole `c` = indeks poprawnej odpowiedzi, `w` = uzasadnienie. */
window.BANK = {
  topics: [
    {
      id: 'czlowiek',
      name: 'Człowiek — możliwości i ograniczenia',
      short: 'Człowiek',
      icon: 'human',
      q: [
        {
          q: 'Wraz ze wzrostem wysokości ciśnienie:',
          o: [
            'rośnie, co wpływa na zaburzenia pracy serca',
            'maleje, w następstwie czego mogą wystąpić objawy choroby wysokościowej',
            'jest stałe i nie ma znaczenia dla organizmu pilota',
            'rośnie, ale zmiana jest tak mała, że nie wpływa na pracę organizmu pilota',
          ],
          c: 1,
          w: 'Ciśnienie spada z wysokością (ok. 1 hPa na 8 m przy ziemi), a wraz z nim ciśnienie parcjalne tlenu — stąd choroba wysokościowa.',
        },
        {
          q: 'Niedotlenienie organizmu podczas wykonywania lotu:',
          o: [
            'może wystąpić na skutek przebywania na dużej wysokości',
            'może spowodować zaburzenia pracy błędnika',
            'ma wpływ na bezpieczeństwo wykonywania lotu',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'Hipoksja pojawia się na wysokości, zaburza błędnik i ocenę sytuacji — wszystkie trzy stwierdzenia są prawdziwe.',
        },
        {
          q: 'Pilot wykonujący lot na paralotni powinien:',
          o: [
            'dopasować swój ubiór do warunków atmosferycznych',
            'zabezpieczyć się przed nadmierną utratą ciepła',
            'korzystać z nieprzewiewnego kombinezonu',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'Temperatura spada z wysokością, a pozorny wiatr dodatkowo wychładza — ubiór musi chronić przed zimnem i przewiewem.',
        },
        {
          q: 'Chwilowe osłabienie słuchu może być skutkiem:',
          o: ['nagłej zmiany ciśnienia', 'nagłej zmiany prędkości', 'zmiany temperatury', 'wszystkie odpowiedzi są prawidłowe'],
          c: 0,
          w: 'Za osłabienie słuchu odpowiada różnica ciśnień po obu stronach błony bębenkowej — wyrównuje się ją np. próbą Valsalvy.',
        },
        {
          q: 'W normalnym stanie atmosfery temperatura powietrza:',
          o: [
            'rośnie, co może doprowadzić do przegrzania organizmu',
            'nie zmienia się',
            'maleje od 0,6 do 1 stopnia na każde 100 m',
            'początkowo rośnie, później maleje',
          ],
          c: 2,
          w: 'Gradient pionowy temperatury wynosi ok. 0,65°C/100 m (do 1°C/100 m w powietrzu suchym).',
        },
        {
          q: 'Prędkość wiatru i jego kierunek:',
          o: [
            'nie ma wpływu na bezpieczeństwo lotu',
            'podczas startu nie ma znaczenia',
            'nie ma wpływu na tworzenie się turbulencji i rotorów',
            'wszystkie odpowiedzi są fałszywe',
          ],
          c: 3,
          w: 'Wiatr decyduje o bezpieczeństwie startu, o rotorach i turbulencji — każde z trzech pierwszych zdań jest nieprawdziwe.',
        },
        {
          q: 'Spożywanie alkoholu przed lub w trakcie lotu:',
          o: [
            'jest łamaniem prawa lotniczego',
            'powoduje pogorszenie koncentracji',
            'niekorzystnie wpływa na narząd równowagi',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'Alkohol jest zakazany przepisami, obniża koncentrację i zaburza błędnik.',
        },
        {
          q: 'Najczęstszą przyczyną urazu kręgosłupa jest:',
          o: [
            'wykonywanie lotów z napędem plecakowym',
            'latanie w kominach termicznych',
            '„przeciągnięcie” paralotni podczas podejścia do lądowania',
            'lądowanie z założonymi „uszami”',
          ],
          c: 2,
          w: 'Przeciągnięcie tuż nad ziemią kończy się pionowym upadkiem na plecy — to klasyczny mechanizm urazu kompresyjnego kręgosłupa.',
        },
        {
          q: 'Start na paralotni może być niebezpieczny, gdy:',
          o: [
            'występuje silny, porywisty wiatr',
            'przez startowisko przechodzą podmuchy termiczne',
            'startowisko jest po stronie zawietrznej góry',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'Porywy, cykle termiczne i strona zawietrzna to trzy typowe pułapki startowiska.',
        },
        {
          q: 'Udzielając pomocy pilotowi, który spadł na ziemię i doznał urazu:',
          o: [
            'jeżeli jest taka potrzeba, staramy się przywrócić akcję serca i oddech',
            'tamujemy miejsca krwotoku',
            'wzywamy służby medyczne',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'Kolejność jest standardowa: funkcje życiowe, krwotoki, wezwanie pomocy.',
        },
      ],
    },
    {
      id: 'meteo',
      name: 'Meteorologia',
      short: 'Meteo',
      icon: 'cloud',
      q: [
        {
          q: 'Front atmosferyczny jest to:',
          o: [
            'linia rozdziału dwóch mas powietrza o różnej temperaturze',
            'linia łącząca punkty o stałym ciśnieniu',
            'obszar występowania powietrza o obniżonym ciśnieniu',
            'masa powietrza przemieszczająca się od wyżu do niżu',
          ],
          c: 0,
          w: 'Front to strefa styku dwóch mas powietrza różniących się temperaturą i wilgotnością.',
        },
        {
          q: 'Po przejściu frontu cieplnego następuje:',
          o: [
            'poprawa pogody, zanikają opady, zwiększa się nasłonecznienie',
            'pogorszenie pogody, mogą pojawić się opady z nimbostratusa',
            'nasilenie opadów z cumulonimbusa',
            'gwałtowne ochłodzenie',
          ],
          c: 1,
          w: 'Front ciepły daje rozległe zachmurzenie warstwowe i jednostajny opad z Ns. Cumulonimbus i gwałtowne ochłodzenie to front chłodny.',
        },
        {
          q: 'Obszar wyżowy to:',
          o: [
            'obszar występowania powietrza, którego temperatura jest stała na każdej wysokości',
            'miejsce występowania powietrza o podwyższonym ciśnieniu',
            'miejsce występowania powietrza o obniżonym ciśnieniu',
            'obszar powietrza powyżej 1500 m n.p.m.',
          ],
          c: 1,
          w: 'Wyż (antycyklon) to obszar podwyższonego ciśnienia z osiadaniem powietrza.',
        },
        {
          q: 'Izobara jest to:',
          o: [
            'linia na mapie pogody łącząca punkty o tym samym ciśnieniu',
            'zapis zmiany ciśnienia na osi czasowej',
            'obszar występowania powietrza o jednakowym ciśnieniu',
            'przyrząd do pomiaru ciśnienia atmosferycznego',
          ],
          c: 0,
          w: 'Izobara łączy punkty o równym ciśnieniu — gęsto ułożone izobary oznaczają silny wiatr.',
        },
        {
          q: 'Okluzja występuje, gdy:',
          o: [
            'nastąpi wyrównanie ciśnienia pomiędzy wyżem a niżem',
            'powietrze o wyższej temperaturze napłynie na obszar chłodniejszego powietrza',
            'front chłodny dogoni front ciepły',
            'powietrze chłodne znajdzie się niżej od ciepłego',
          ],
          c: 2,
          w: 'Szybszy front chłodny dogania ciepły i wypycha ciepłe powietrze w górę — powstaje front zokludowany.',
        },
        {
          q: 'Chmura cb:',
          o: [
            'powoduje gwałtowny opad',
            'towarzyszą jej silne prądy powietrzne',
            'jest dużym zagrożeniem dla pilota paralotniowego',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'Cb to chmura burzowa: nawalny opad, prądy rzędu kilkunastu m/s, zasysanie — bezwzględny zakaz latania.',
        },
        {
          q: 'Chmura nimbostratus:',
          o: [
            'jest chmurą najniższego piętra',
            'zbudowana jest z wody i pary wodnej',
            'powoduje jednostajny opad deszczu',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'Ns to niska, gruba chmura warstwowa dająca ciągły opad — typowa dla frontu ciepłego.',
        },
        {
          q: 'Chmura altus:',
          o: [
            'sygnalizuje gwałtowne pogorszenie pogody',
            'nie występuje w naszej strefie klimatycznej',
            'zbudowana jest wyłącznie z pary wodnej',
            'jest chmurą średniego piętra',
          ],
          c: 3,
          w: 'Przedrostek „alto-” oznacza piętro średnie, ok. 2000–7000 m.',
        },
        {
          q: 'Chmura cirrus:',
          o: [
            'zbudowana jest z kryształków lodu',
            'jest chmurą średniego piętra',
            'łatwo przeobraża się w chmurę burzową',
            'występuje głównie zimą',
          ],
          c: 0,
          w: 'Cirrus to chmura piętra wysokiego zbudowana z kryształków lodu.',
        },
        {
          q: 'Inwersja to:',
          o: [
            'zjawisko wyrównania ciśnienia pomiędzy sąsiadującymi dolinami',
            'zjawisko pogodowe, w którym powietrze o wyższej temperaturze znajduje się wyżej',
            'efekt przepływu powietrza przez dyszę',
            'forma rotoru',
          ],
          c: 1,
          w: 'Inwersja to wzrost temperatury z wysokością — działa jak sufit blokujący termikę.',
        },
      ],
    },
    {
      id: 'nawigacja',
      name: 'Nawigacja',
      short: 'Nawigacja',
      icon: 'compass',
      q: [
        {
          q: 'Godzina 1:00 czasu lokalnego latem w Polsce:',
          o: ['24:00 UTC dnia poprzedniego', '1:00 UTC', '11:00 UTC', '23:00 UTC dnia poprzedniego'],
          c: 3,
          w: 'Latem w Polsce obowiązuje UTC+2, więc 1:00 lokalnie = 23:00 UTC dnia poprzedniego.',
        },
        {
          q: 'Planując przelot na paralotni, pilot powinien:',
          o: [
            'przeanalizować warunki meteorologiczne',
            'zaplanować miejsca awaryjnego lądowania',
            'uwzględnić ograniczenia w ruchu lotniczym',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'Pogoda, lądowiska awaryjne i przestrzeń powietrzna to trzy filary planowania przelotu.',
        },
        {
          q: 'Jaki kierunek określany jest jako SE:',
          o: ['095', '315', '045', '135'],
          c: 3,
          w: 'Południowy wschód to 135°. 045° = NE, 315° = NW.',
        },
        {
          q: 'Jaki kierunek określany jest jako NW:',
          o: ['315', '295', '335', '205'],
          c: 0,
          w: 'Północny zachód to 315°.',
        },
        {
          q: 'Wiatr boczny:',
          o: [
            'uniemożliwia lot na wprost',
            'wydłuża czas lotu do celu',
            'nie ma wpływu na czas przelotu',
            'powoduje znaczne zwiększenie opadania',
          ],
          c: 1,
          w: 'Aby utrzymać kurs, trzeba lecieć z poprawką na znoszenie — część prędkości „ucieka” na kompensację, więc lot trwa dłużej.',
        },
        {
          q: 'Wykonując lot docel-powrót przy silnym wietrze:',
          o: [
            'czas lotu będzie taki sam jak przy bezwietrzu',
            'w zależności czy wracamy z wiatrem, czy pod wiatr, lot będzie dłuższy lub krótszy niż przy bezwietrzu',
            'czas przelotu będzie zawsze krótszy',
            'czas przelotu będzie zawsze dłuższy',
          ],
          c: 3,
          w: 'Na trasie tam i z powrotem strata pod wiatr jest zawsze większa niż zysk z wiatrem — łączny czas rośnie.',
        },
        {
          q: 'Paralotnia lecąc w powietrzu z prędkością trymową ma stałą prędkość:',
          o: [
            'w stosunku do powierzchni ziemi',
            'w stosunku do otaczającego powietrza',
            'nie wytraca wysokości',
            'ma większą prędkość, gdy sterówki są zaciągnięte',
          ],
          c: 1,
          w: 'Prędkość paralotni to zawsze prędkość względem masy powietrza (IAS); prędkość nad ziemią zależy dodatkowo od wiatru.',
        },
        {
          q: 'Lecąc zgodnie z kierunkiem wiatru, pilot ma prędkość w odniesieniu do ziemi:',
          o: [
            'będącą sumą prędkości własnej i prędkości wiatru',
            'konstrukcyjną paralotni',
            'trymową',
            'żadna z odpowiedzi nie jest prawidłowa',
          ],
          c: 0,
          w: 'Z wiatrem prędkości się dodają: GS = prędkość własna + prędkość wiatru.',
        },
        {
          q: 'Za pomocą GPS możemy określić:',
          o: [
            'nasze położenie względem ziemi',
            'prędkość w odniesieniu do powierzchni ziemi',
            'odległość od miejsca planowanego lądowania',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'GPS podaje pozycję, prędkość względem ziemi (GS) i odległości do punktów trasy.',
        },
        {
          q: 'Altimetr służy do pomiaru:',
          o: [
            'prędkości paralotni względem powietrza',
            'prędkości paralotni w odniesieniu do powierzchni ziemi',
            'ustalenia kierunku lotu',
            'pomiaru wysokości',
          ],
          c: 3,
          w: 'Wysokościomierz mierzy wysokość — najczęściej barometrycznie, po ustawieniu ciśnienia odniesienia (QNH).',
        },
      ],
    },
    {
      id: 'prawo',
      name: 'Prawo lotnicze',
      short: 'Prawo',
      icon: 'law',
      q: [
        {
          q: 'Dokumentem uprawniającym do wykonywania lotów na paralotni jest:',
          o: [
            'karta pilota paralotniowego',
            'Świadectwo Kwalifikacji Pilota Paralotniowego',
            'legitymacja FAI',
            'ubezpieczenie OC',
          ],
          c: 1,
          w: 'Świadectwo kwalifikacji (ŚK) wydaje Prezes Urzędu Lotnictwa Cywilnego.',
        },
        {
          q: 'Świadectwo Kwalifikacji Pilota Paralotniowego wydawane jest na okres:',
          o: ['5 lat', 'bezterminowo', '10 lat', 'w zależności od wieku pilota'],
          c: 1,
          w: 'Samo świadectwo jest bezterminowe — ograniczoną ważność mają wpisane do niego uprawnienia.',
        },
        {
          q: 'Uprawnienia podstawowe wpisywane do ŚK to:',
          o: ['PP, PPG, PPGG', 'PP, PPG', 'TANDEM, INS', 'wszystkie wyżej wymienione'],
          c: 0,
          w: 'PP — paralotnia, PPG — paralotnia z napędem, PPGG — paralotnia z napędem na wózku. TANDEM i INS to uprawnienia dodatkowe.',
        },
        {
          q: 'Loty paralotniowe można wykonywać w okresie:',
          o: [
            'od wschodu do zachodu słońca',
            '30 min przed wschodem słońca do 30 min po zachodzie słońca',
            'od 22 marca do 24 grudnia',
            'różnie, w zależności od posiadanego uprawnienia',
          ],
          c: 0,
          w: 'Loty na paralotni wykonuje się wyłącznie w dzień, w warunkach VFR — od wschodu do zachodu słońca.',
        },
        {
          q: 'Jakie warunki powinien spełniać kandydat do szkolenia paralotniowego:',
          o: [
            'powinien być pełnoletni',
            'nie ma ograniczeń wiekowych',
            'ukończone 15 lat i za zgodą prawnych opiekunów',
            'ukończone 17 lat',
          ],
          c: 2,
          w: 'Szkolenie można rozpocząć od 15. roku życia za pisemną zgodą opiekunów; świadectwo wydaje się po ukończeniu 16 lat.',
        },
        {
          q: 'Za teren zabudowany w lotach paralotniowych uważa się:',
          o: ['zabudowaną część terenu miejskiego', 'zgrupowanie ludzi', 'obszar zabudowany', 'wszystkie odpowiedzi są prawidłowe'],
          c: 3,
          w: 'Pojęcie obejmuje miasta, osiedla i każde zgromadzenie ludzi na wolnym powietrzu.',
        },
        {
          q: 'Loty nad terenem zabudowanym można wykonywać na wysokości:',
          o: ['> 50 m', '> 100 m', '> 150 m licząc od powierzchni ziemi', '> 150 m licząc od najwyższego obiektu w promieniu 300 m'],
          c: 3,
          w: 'Odniesieniem jest najwyższa przeszkoda w określonym promieniu, a nie sam poziom gruntu.',
        },
        {
          q: 'Loty VFR to:',
          o: ['loty nocne', 'loty w strefie', 'loty z wizualizacją przestrzeni', 'nie dotyczy paralotniarzy'],
          c: 2,
          w: 'VFR (Visual Flight Rules) — loty z widocznością ziemi i przestrzeni, prowadzone wizualnie.',
        },
        {
          q: 'Loty w strefie EP D:',
          o: [
            'są bezwzględnie zakazane',
            'mogą być wykonywane tylko w lotach bez napędu',
            'można wykonywać, o ile strefa nie została aktywowana',
            'można wykonywać za zgodą właściciela terenu',
          ],
          c: 2,
          w: 'EP D to strefa niebezpieczna — obowiązuje tylko w czasie aktywacji; bezwzględny zakaz dotyczy EP P.',
        },
        {
          q: 'Loty na paralotni można wykonywać do wysokości:',
          o: ['nie ma ograniczeń', 'do 2900 m, o ile nie występują inne ograniczenia', '1500 m w EP P', '3000 m, ale tylko w EP R'],
          c: 1,
          w: 'Przestrzeń niekontrolowana klasy G sięga w Polsce do 2900 m AMSL (FL 095).',
        },
      ],
    },
    {
      id: 'zasady',
      name: 'Zasady lotu',
      short: 'Zasady lotu',
      icon: 'wing',
      q: [
        {
          q: 'B-stall:',
          o: [
            'służy do uzyskania większego opadania',
            'wykonujemy zaciągając taśmy rzędu B',
            'jest stanem mało stabilnym i dlatego wymaga przy stosowaniu dużej ostrożności',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'B-stall to celowe zerwanie strug przez zaciągnięcie taśm B — daje duże opadanie, ale jest stanem niestabilnym.',
        },
        {
          q: 'Spiralą nazywamy taki stan lotu, w którym:',
          o: [
            'paralotnia obraca się wokół osi pionowej',
            'paralotnia obraca się wokół osi poziomej',
            'następuje jednostronne przeciągnięcie',
            'założymy z jednej strony podwinięcie',
          ],
          c: 0,
          w: 'W spirali skrzydło leci po stromej spirali wokół osi pionowej, z dużym przeciążeniem i opadaniem.',
        },
        {
          q: 'Przy luźnych linkach sterowniczych:',
          o: [
            'paralotnia posiada największą prędkość postępową',
            'paralotnia uzyskuje prędkość trymową',
            'paralotnia osiąga największą wartość siły nośnej',
            'żadna odpowiedź nie jest prawidłowa',
          ],
          c: 1,
          w: 'Bez ingerencji w sterówki skrzydło leci z prędkością trymową; większą prędkość daje dopiero przyśpieszacz.',
        },
        {
          q: 'Zwiększenie kąta natarcia:',
          o: [
            'nie ma wpływu na prędkość paralotni',
            'może spowodować podwinięcie czołowe',
            'stosujemy przy lądowaniu aby wyhamować postępową paralotni',
            'zwiększa ryzyko wystąpienia podwinięć bocznych',
          ],
          c: 2,
          w: 'Zaciągnięcie sterówek zwiększa kąt natarcia i hamuje skrzydło — to podstawa flare przy lądowaniu. Podwinięcia grożą przy zmniejszonym kącie natarcia.',
        },
        {
          q: 'Krytyczny kąt natarcia to kąt, przy którym paralotnia:',
          o: [
            'wyhamuje prędkość do wartości zerowej',
            'traci strugi na całej górnej powierzchni skrzydła',
            'ulega zniszczeniu na skutek przeciążenia',
            'uzyskuje największą wartość prędkości postępowej',
          ],
          c: 1,
          w: 'Po przekroczeniu kąta krytycznego następuje oderwanie strug na górnej powierzchni i przeciągnięcie.',
        },
        {
          q: 'Co się dzieje, gdy spada gęstość powietrza (np. z wysokością):',
          o: [
            'siła nośna skrzydła maleje',
            'siła nośna skrzydła rośnie',
            'siła nośna skrzydła jest stała niezależnie od warunków atmosferycznych',
            'maleje opadanie paralotni',
          ],
          c: 0,
          w: 'Siła nośna jest wprost proporcjonalna do gęstości powietrza (L = Cz · ½ρV² · S).',
        },
        {
          q: 'Opór powietrza zależny jest od:',
          o: ['powierzchni skrzydła', 'gęstości powietrza', 'prędkości lotu', 'wszystkie odpowiedzi są prawidłowe'],
          c: 3,
          w: 'Opór: D = Cx · ½ρV² · S — zależy od powierzchni, gęstości i kwadratu prędkości.',
        },
        {
          q: 'Gdy prędkość paralotni rośnie, to:',
          o: [
            'spada opór aerodynamiczny',
            'rośnie opór aerodynamiczny',
            'opór aerodynamiczny nie ulega zmianie i jest stały w całym zakresie prędkości',
            'wszystkie odpowiedzi są fałszywe',
          ],
          c: 1,
          w: 'Opór szkodliwy rośnie z kwadratem prędkości — dlatego na przyśpieszaczu gwałtownie rośnie opadanie.',
        },
        {
          q: 'Opór indukowany:',
          o: [
            'na paralotni nie występuje',
            'posiada stałą wartość dla danego profilu',
            'jest tym większy nim końcówka skrzydła jest szersza',
            'jest tym większy nim końcówka skrzydła jest węższa',
          ],
          c: 2,
          w: 'Opór indukowany powstaje na końcówkach skrzydła — im szersza końcówka (mniejsze wydłużenie), tym silniejsze wiry i większy opór.',
        },
        {
          q: 'Kątem natarcia nazywamy:',
          o: [
            'kąt zawarty pomiędzy cięciwą skrzydła a kierunkiem napływających strug',
            'kąt zawarty pomiędzy cięciwą skrzydła a poziomem ziemi',
            'kąt zawarty pomiędzy cięciwą skrzydła a linią łączącą krawędź natarcia z krawędzią spływu',
            'kąt zawarty pomiędzy stycznymi do powierzchni dolnej i górnej paralotni',
          ],
          c: 0,
          w: 'Kąt natarcia to kąt między cięciwą profilu a kierunkiem napływu powietrza — nie ma nic wspólnego z poziomem ziemi.',
        },
      ],
    },
    {
      id: 'bezpieczenstwo',
      name: 'Bezpieczeństwo lotów',
      short: 'Bezpieczeństwo',
      icon: 'shield',
      q: [
        {
          q: 'Wyprowadzenie paralotni z korkociągu (negatywki) wykonujemy poprzez:',
          o: [
            'wprowadzenie skrzydła w fazę full-stall i wyjście standardowe',
            'nie reagujemy, skrzydło wyprowadzi się samo',
            'zaciągamy mocno sterówkę po stronie wewnętrznej',
            'wszystkie odpowiedzi są fałszywe',
          ],
          c: 0,
          w: 'Rozwinięty korkociąg wygasza się przez symetryczne przeciągnięcie i standardowe wyjście z full-stalla. Dociągnięcie sterówki wewnętrznej pogłębia rotację.',
        },
        {
          q: 'Jeżeli skrzydło ulegnie przeciągnięciu i opada za plecami, to:',
          o: [
            'szybko, ale płynnie odpuszczamy sterówki',
            'w razie potrzeby, gdy skrzydło wyprzedza, lekko przyhamowujemy',
            'brak reakcji pilota może spowodować sytuację, w której wskazane zostanie użycie SIP',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'Płynne odpuszczenie, kontrola wyprzedzenia i świadomość, że zwłoka kończy się użyciem spadochronu — wszystkie zdania są prawdziwe.',
        },
        {
          q: 'Paralotnia sygnalizuje moment przeciągnięcia (full stall) poprzez:',
          o: [
            'zanik odgłosu świstu powietrza przelatującego przez olinowanie',
            'rosnącą siłę na sterówkach',
            'znaczną utratę prędkości postępowej',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'Cisza w olinowaniu, narastający opór sterówek i zanik prędkości to klasyczne objawy zbliżania się do przeciągnięcia.',
        },
        {
          q: 'Przeciągnięcie paralotni (przejście przez krytyczny kąt natarcia) wystąpi, gdy:',
          o: [
            'nadmiernie rozpędzimy paralotnię',
            'zbyt mocno zaciągniemy sterówki',
            'zbyt szybko uwolnimy sterówki po spadochronowaniu ustalonym',
            'podczas startu zbyt mocno wypychamy taśmę A do przodu',
          ],
          c: 1,
          w: 'Kąt natarcia rośnie wraz z zaciąganiem sterówek — jego przekroczenie oznacza przeciągnięcie.',
        },
        {
          q: 'W trakcie lotu prawa część paralotni ulega podwinięciu:',
          o: [
            'natychmiast uruchamiamy SIP',
            'nie reagujemy, paralotnia samoczynnie wyjdzie z sytuacji niebezpiecznej',
            'balansujemy ciałem na lewą stronę i w razie potrzeby lekko zaciągamy lewą sterówkę',
            'zaciągamy obie sterówki o 30%',
          ],
          c: 2,
          w: 'Najpierw kurs: ciężarem i delikatnym hamulcem po stronie otwartej powstrzymujemy obrót, dopiero potem otwieramy podwinięcie.',
        },
        {
          q: 'Kask jest wyposażeniem:',
          o: ['obowiązkowym', 'dobrowolnym', 'wymaganym tylko w lotach z pasażerem', 'obowiązkowym tylko w przypadku lotów szkoleniowych'],
          c: 0,
          w: 'Kask jest obowiązkowym elementem wyposażenia pilota paralotni.',
        },
        {
          q: 'Protektor w uprzęży paralotniowej:',
          o: [
            'jest obowiązkowy',
            'łagodzi skutki upadku z wysokości',
            'poprawia komfort użytkowania uprzęży',
            'umożliwia zamocowanie kółek',
          ],
          c: 1,
          w: 'Zadaniem protektora (pianka, airbag) jest pochłonięcie energii uderzenia przy twardym lądowaniu lub upadku.',
        },
        {
          q: 'Spadochron ratunkowy SIP:',
          o: [
            'używamy w przypadku zderzenia paralotniarzy',
            'używamy w przypadku uszkodzenia paralotni uniemożliwiającego dalszy lot',
            'używamy w przypadku trwałego odkształcenia paralotni uniemożliwiającego dalszy lot',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'SIP otwieramy zawsze, gdy skrzydło przestaje być sterowne — niezależnie od przyczyny.',
        },
        {
          q: 'W przypadku konieczności szybkiego wytracenia wysokości stosujemy:',
          o: ['uszy', 'B-stall', 'spirala', 'wszystkie odpowiedzi są prawidłowe'],
          c: 3,
          w: 'To trzy podstawowe techniki szybkiego opadania, różniące się skutecznością i ryzykiem.',
        },
        {
          q: 'Podczas startu w fazie rozbiegu środkowa część czaszy jest cofnięta:',
          o: [
            'lekko przyhamowujemy paralotnię i kontynuujemy rozbieg',
            'natychmiast przerywamy start',
            'mocno hamujemy i gwałtownie przyśpieszamy',
            'kontynuujemy rozbieg z poluzowanymi sterówkami',
          ],
          c: 1,
          w: 'Niepoprawnie wypełnione skrzydło to powód do natychmiastowego przerwania startu — kontrola czaszy przed oderwaniem jest obowiązkowa.',
        },
      ],
    },
    {
      id: 'osiagi',
      name: 'Osiągi i planowanie lotu',
      short: 'Osiągi',
      icon: 'chart',
      q: [
        {
          q: 'W kominie termicznym podczas przelotu:',
          o: [
            'pozostajemy aż do jego wygaśnięcia',
            'obieramy kierunek krążenia zawsze w prawo',
            'wykorzystujemy wszystkie kominy',
            'wszystkie odpowiedzi są nieprawidłowe',
          ],
          c: 3,
          w: 'Na przelocie wykorzystujemy tylko wybrane, mocne kominy, kierunek krążenia narzuca pierwszy pilot w kominie, a wznoszenie opuszczamy przed jego wygaśnięciem.',
        },
        {
          q: 'Przelot otwarty wykonujemy najczęściej:',
          o: [
            'pod wiatr',
            'nad zbiornikami wodnymi',
            'nad zwartą zabudową, lepsze warunki termiczne',
            'wszystkie odpowiedzi są nieprawidłowe',
          ],
          c: 3,
          w: 'Przelot otwarty planuje się z wiatrem; woda termiki nie daje, a lot nad zwartą zabudową jest niedopuszczalny.',
        },
        {
          q: 'Planując przelot, należy uwzględnić:',
          o: [
            'możliwość awaryjnego lądowania',
            'miejsca występowania kominów termicznych',
            'rzeźbę terenu, nad którym ma się odbyć lot',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'Lądowiska, źródła termiki i ukształtowanie terenu wyznaczają realny przebieg trasy.',
        },
        {
          q: 'Planowanie lotu powinno zawierać:',
          o: [
            'analizę warunków meteorologicznych',
            'sprawdzenie dostępności przestrzeni powietrznej',
            'określenie możliwości psychofizycznych pilota',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'Pogoda, przestrzeń i stan pilota — bez żadnego z tych elementów planowanie jest niepełne.',
        },
        {
          q: 'Użycie przyśpieszacza prędkości „Speed” powoduje:',
          o: [
            'zwiększenie prędkości postępowej',
            'zwiększenie opadania',
            'zmniejszenie doskonałości lotniczej',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'Speed zmniejsza kąt natarcia: rośnie prędkość i opadanie, a doskonałość spada (choć pod wiatr i tak może się opłacać).',
        },
        {
          q: 'Biegunowa skrzydła to:',
          o: [
            'linia łącząca „noski” profilów paralotni',
            'taśma wszyta w komory celem poprawienia sztywności paralotni',
            'miejsce spiętrzenia powietrza w komorach paralotni',
            'wykres zależności prędkości postępowej i opadania',
          ],
          c: 3,
          w: 'Biegunowa (polara) to wykres prędkości opadania w funkcji prędkości postępowej.',
        },
        {
          q: 'Na przedstawionej biegunowej punkt A określa:',
          o: [
            'minimalną bezpieczną prędkość paralotni',
            'najmniejsze opadanie',
            'prędkość ekonomiczną',
            'prędkość trymową',
          ],
          c: 0,
          w: 'Punkt A leży na lewym krańcu biegunowej — to najmniejsza prędkość lotu, tuż przed przeciągnięciem.',
          fig: 'polar',
        },
        {
          q: 'Na przedstawionej biegunowej punkt B określa:',
          o: [
            'prędkość postępową, przy której paralotnia ma najlepszą doskonałość',
            'prędkość postępową, przy której paralotnia ma najmniejsze opadanie',
            'prędkość trymową paralotni',
            'prędkość przeciągnięcia',
          ],
          c: 1,
          w: 'Punkt B to najwyższy punkt krzywej — minimum opadania, prędkość używana do wykręcania termiki.',
          fig: 'polar',
        },
        {
          q: 'Na przedstawionej biegunowej punkt C określa:',
          o: [
            'prędkość postępową, przy której paralotnia posiada najlepszą doskonałość',
            "prędkość maksymalną bez użycia speed'a",
            'prędkość trymową',
            'prędkość preferowaną do manewru lądowania',
          ],
          c: 0,
          w: 'Punkt C to punkt styczności prostej z początku układu z biegunową — najlepsza doskonałość, czyli największy zasięg.',
          fig: 'polar',
        },
        {
          q: 'Na przedstawionej biegunowej punkt D określa:',
          o: [
            'prędkość trymową paralotni',
            "prędkość maksymalną paralotni z użyciem speed'a i trymerów",
            'max bezpieczną prędkość paralotni',
            'prędkość, przy której paralotnia traci strugi',
          ],
          c: 1,
          w: 'Punkt D to prawy koniec biegunowej — maksymalna prędkość osiągana na pełnym przyśpieszaczu i trymerach.',
          fig: 'polar',
        },
      ],
    },
    {
      id: 'procedury',
      name: 'Procedury operacyjne',
      short: 'Procedury',
      icon: 'checklist',
      q: [
        {
          q: 'Lot paralotniowy można wykonać:',
          o: [
            'wyłącznie po uzyskaniu zgody służb dozoru ruchu lotniczego',
            'po złożeniu w ULC planu lotu',
            'do wysokości 1500 m',
            'wszystkie odpowiedzi są nieprawidłowe',
          ],
          c: 3,
          w: 'W przestrzeni niekontrolowanej nie trzeba zgody ATC ani planu lotu, a pułap to 2900 m AMSL, nie 1500 m.',
        },
        {
          q: 'Jakie czynności serwisowe zalecają producenci SIP:',
          o: [
            'kontrolę, wietrzenie, przekładanie w regularnych odstępach',
            'raz w roku kontrolne uruchomienie w locie',
            'raz w roku wykonać próby wytrzymałościowe',
            'do 6 miesięcy przesłać system do producenta do kontroli',
          ],
          c: 0,
          w: 'Spadochron ratunkowy wymaga okresowego wietrzenia i ponownego przełożenia — zwykle co 6–12 miesięcy.',
        },
        {
          q: 'Pilot paralotni może lądować:',
          o: [
            'wyłącznie na oficjalnych lądowiskach',
            'tylko w miejscach oznaczonych rękawem lotniczym',
            'po uzyskaniu zgody ULC',
            'w miejscach przygodnych, ale w razie naruszenia mienia obowiązuje kodeks cywilny',
          ],
          c: 3,
          w: 'Lądowanie w terenie przygodnym jest dozwolone; za ewentualne szkody pilot odpowiada na zasadach ogólnych.',
        },
        {
          q: 'Lądowanie na zboczu wykonujemy:',
          o: ['zawsze pod wiatr', 'pod stok', 'zgodnie ze spadkiem stoku', 'w poprzek stoku'],
          c: 3,
          w: 'Na zboczu lądujemy w poprzek stoku, czyli wzdłuż warstwicy. Podejście prosto pod górę wprowadza skrzydło w podnoszący się teren, a zgodnie ze spadkiem — w teren uciekający spod nóg.',
        },
        {
          q: 'Na podejściu do lądowania:',
          o: [
            'pierwszeństwo posiada pilot będący niżej',
            'należy przyhamować paralotnię i przejść do spadochronowania',
            'zawsze zakładamy uszy',
            'korzystamy z systemu hamującego SIP',
          ],
          c: 0,
          w: 'Pierwszeństwo ma statek powietrzny znajdujący się niżej — on ma mniej możliwości manewru.',
        },
        {
          q: 'Kontrolę przedstartową paralotni i zapięć uprzęży należy wykonać:',
          o: ['po przeglądzie okresowym', 'zawsze bezpośrednio przed startem', 'w trakcie wykonywania startu', 'bezpośrednio po starcie'],
          c: 1,
          w: 'Check przedstartowy wykonuje się bezpośrednio przed każdym startem — to ostatni moment na wykrycie błędu.',
        },
        {
          q: 'Pilot paralotni przed startem powinien:',
          o: [
            'sprawdzić, czy miejsce startu pozbawione jest przeszkód',
            'startowisko usytuowane jest pod wiatr',
            'sprawdzić, czy przestrzeń nad startowiskiem nie jest zajęta',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'Przeszkody, wiatr i ruch nad startowiskiem to trzy elementy oceny przed każdym startem.',
        },
        {
          q: 'Jakie z wymienionych dokumentów pilot paralotni powinien mieć przy sobie:',
          o: ['dowód osobisty', 'ubezpieczenie KL', 'świadectwo kwalifikacji', 'świadectwo lekarskie'],
          c: 2,
          w: 'Podczas lotów pilot ma przy sobie świadectwo kwalifikacji z ważnymi uprawnieniami.',
        },
        {
          q: 'W trakcie lotu żaglowego:',
          o: [
            'pilot robi zwrot zawsze w kierunku stoku',
            'pilot tandemu ma pierwszeństwo',
            'nawrót wykonuje się od stoku',
            'wyprzedzamy zawsze z prawej strony',
          ],
          c: 2,
          w: 'Nawrót zawsze wykonuje się w stronę od zbocza — zwrot do stoku grozi zderzeniem ze zboczem.',
        },
        {
          q: 'W kominie termicznym pierwszeństwo posiada pilot:',
          o: ['krążący w prawo', 'będący wyżej', 'pilot tandemu', 'będący niżej'],
          c: 3,
          w: 'Pierwszeństwo ma pilot niżej — pilot wyżej widzi go i dostosowuje kierunek krążenia.',
        },
      ],
    },
    {
      id: 'obsluga',
      name: 'Transport, konserwacja i obsługa statku powietrznego',
      short: 'Konserwacja',
      icon: 'tools',
      q: [
        {
          q: 'W przypadku zanurzenia paralotni w wodzie morskiej:',
          o: [
            'należy ją wypłukać w słodkiej wodzie',
            'wysuszyć w miejscu przewiewnym, ale nie nasłonecznionym',
            'po 2 latach dokonać przeglądu, w tym kontrolę wytrzymałościową olinowania',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'Sól niszczy tkaninę i linki — trzeba je wypłukać, wysuszyć w cieniu i poddać skrzydło przeglądowi.',
        },
        {
          q: 'Paralotnię należy przechowywać:',
          o: [
            'w stanie suchym, zaleca się okresowe wietrzenie',
            'w miejscu nie wyeksponowanym na światło słoneczne',
            'w stanie luźnego złożenia, nie należy niepotrzebnie jej ugniatać',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'Wilgoć, UV i ugniatanie to trzej główni wrogowie tkaniny i powłoki skrzydła.',
        },
        {
          q: 'Skrzydło należy składać komorami:',
          o: [
            'przeciwdziała się w ten sposób zagnieceniom sztywników',
            'w szczególności te, które są wyposażone w żyłkowe usztywnienia',
            'w celu utrzymania wlotów komór w nienaruszonym stanie',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'Składanie „komora w komorę” chroni sztywniki (nylon/żyłka) i kształt wlotów.',
        },
        {
          q: 'Śmigło PPG lub PPGG zabezpieczamy pokrowcem ochronnym:',
          o: [
            'aby zabezpieczyć przed przypadkowym uszkodzeniem krawędzi',
            'aby zabezpieczyć przed opadem deszczu i zakurzeniom',
            'śmigła węglowe i kompozytowe są wrażliwe na promieniowanie UV, a drewniane na wilgoć',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'Pokrowiec chroni krawędzie, powierzchnię i strukturę materiału śmigła.',
        },
        {
          q: 'Uprząż paralotniowa:',
          o: [
            'podlega corocznie obowiązkowemu przeglądowi',
            'powinna być wymieniana co 5 lat',
            'nie podlega przeglądom, ale co 3 lata należy wymienić karabinki nośne',
            'wszystkie odpowiedzi są nieprawidłowe',
          ],
          c: 3,
          w: 'Nie ma sztywnego rocznego przeglądu ani obowiązku wymiany co 5 lat — obowiązują zalecenia producenta i bieżąca ocena stanu.',
        },
        {
          q: 'Skrzydło paralotni podlega przeglądowi:',
          o: [
            'po zdarzeniu, w którym mogło dojść do naruszenia jej struktury',
            'jeżeli lot wykonuje uczeń lub jest to lot w tandemie',
            'dla wiedzy pilota na temat stanu technicznego',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'Przegląd robi się po incydencie, przy eksploatacji szkoleniowej i tandemowej oraz okresowo dla własnego bezpieczeństwa.',
        },
        {
          q: 'Jeżeli skrzydło paralotni ulegnie pobrudzeniu:',
          o: [
            'można je wyprać w pralce',
            'do czyszczenia używamy detergentów',
            'po wypraniu suszymy na słońcu',
            'wszystkie odpowiedzi są fałszywe',
          ],
          c: 3,
          w: 'Pralka, detergenty i suszenie na słońcu niszczą powłokę tkaniny — czyścimy tylko czystą wodą i suszymy w cieniu.',
        },
        {
          q: 'Wózek motoparalotni transportujemy:',
          o: [
            'na dachu samochodu, tyłem do przodu',
            'w pozycji pionowej, tak aby ładunek był jak najkrótszy',
            'na specjalnie przygotowanym wózku lub przyczepie',
            'ciągnąc za samochodem na haku',
          ],
          c: 2,
          w: 'Wózek przewozi się na przyczepie lub dedykowanej platformie, unieruchomiony i zabezpieczony.',
        },
        {
          q: 'Kiedy należy przygotować mieszankę do silnika dwusuwowego:',
          o: [
            'nie ma specjalnych zaleceń',
            'najlepiej wymieszać z 3-miesięcznym wyprzedzeniem',
            'bezpośrednio przed lotem',
            'do silników dwusuwowych nie ma potrzeby stosować mieszanki paliwowej',
          ],
          c: 2,
          w: 'Mieszanka się rozwarstwia i starzeje — przygotowuje się ją na bieżąco, bezpośrednio przed lotem.',
        },
        {
          q: 'Konserwacja i obsługa SIP polega na:',
          o: [
            'wysuszeniu go na słońcu i ponownemu rozłożeniu',
            'przepraniu z dodatkiem płynu antyelektrostatycznego i wysuszeniu na słońcu',
            'regularnym wietrzeniu i składaniu wg instrukcji producenta',
            'okresowej wymianie olinowania',
          ],
          c: 2,
          w: 'Spadochron ratunkowy wietrzy się i przekłada zgodnie z instrukcją producenta — nie pierze i nie suszy na słońcu.',
        },
      ],
    },
    {
      id: 'wiedza',
      name: 'Wiedza ogólna o statku powietrznym',
      short: 'Sprzęt',
      icon: 'glider',
      q: [
        {
          q: 'Wydłużeniem paralotni nazywamy:',
          o: [
            'stosunek rozpiętości czaszy do jej cięciwy',
            'stosunek rozpiętości czaszy do jej powierzchni',
            'stosunek kwadratu rozpiętości do powierzchni',
            'powiększenie wymiarów paralotni na skutek jej użytkowania',
          ],
          c: 2,
          w: 'Wydłużenie AR = b² / S. Większe wydłużenie to lepsza doskonałość, ale mniejsza odporność na podwinięcia.',
        },
        {
          q: 'Aby przeciwdziałać nadmiernemu zużyciu paralotni:',
          o: [
            'nie należy bez potrzeby wystawiać jej na działanie UV',
            'regularnie prać tkaninę',
            'okresowo impregnować',
            'przechowywać w szczelnym zamknięciu',
          ],
          c: 0,
          w: 'Promieniowanie UV to główny czynnik niszczący tkaninę; prania i impregnacji się nie stosuje.',
        },
        {
          q: 'Sterówka to:',
          o: [
            'uchwyt mocowany do taśm A',
            'linka łącząca uchwyt sterowniczy z galeryjką linek odchodzącą od krawędzi spływu',
            'część taśmy A',
            'urządzenie służące do nawigacji',
          ],
          c: 1,
          w: 'Sterówka (hamownia) ciągnie krawędź spływu przez galeryjkę linek — deformuje tylną część profilu.',
        },
        {
          q: 'Otwory wyrównawcze:',
          o: [
            'służą do wyrównywania ciśnienia między komorami',
            'są wycięte w profilach',
            'mają wpływ na skuteczność wypełniania się czaszy paralotni',
            'wszystkie odpowiedzi są prawidłowe',
          ],
          c: 3,
          w: 'Otwory w żebrach łączą komory, wyrównują ciśnienie i przyspieszają napełnianie skrzydła.',
        },
        {
          q: 'Speed-System to:',
          o: [
            'dodatkowe dwie komory doszyte do końcówek skrzydła',
            'urządzenie do pomiaru prędkości wiatru',
            'przyśpieszacz prędkości zamontowany na taśmie A',
            'przyśpieszacz prędkości zamontowany na taśmie D',
          ],
          c: 2,
          w: 'Przyśpieszacz skraca przednie taśmy (A, częściowo B), zmniejszając kąt natarcia.',
        },
        {
          q: 'Paralotnia posiadająca atest EN A, DHV 1 lub AFNOR standard to:',
          o: [
            'paralotnia szkolno-rekreacyjna',
            'paralotnia wyczynowa',
            'paralotnia przeznaczona do lotów z napędem',
            'paralotnia o nieokreślonych właściwościach',
          ],
          c: 0,
          w: 'Najniższa klasa atestu oznacza skrzydło o największej odporności na błędy pilota — szkolne i rekreacyjne.',
        },
        {
          q: 'Paralotnia o profilu samostatecznym:',
          o: [
            'ułatwia krążenie w kominie termicznym',
            'może być używana wyłącznie przez doświadczonych pilotów',
            'przeznaczona jest do lotów z napędem',
            'wymaga użycia specjalnej uprzęży',
          ],
          c: 2,
          w: 'Profil samostateczny (reflex) utrzymuje dodatni moment przy małym kącie natarcia — to rozwiązanie skrzydeł napędowych PPG.',
        },
        {
          q: 'Materiał, z którego uszyta jest paralotnia, powinien spełniać następujące kryteria:',
          o: ['wytrzymałości mechanicznej', 'odporności na przenikanie cząstek powietrza', 'gładkości powierzchni', 'wszystkie odpowiedzi są prawidłowe'],
          c: 3,
          w: 'Tkanina musi być wytrzymała, szczelna i gładka — inaczej skrzydło traci kształt i osiągi.',
        },
        {
          q: 'Masa startowa to:',
          o: ['waga pilota w ubraniu', 'waga pilota i uprzęży', 'waga paralotni', 'waga całości będącej w powietrzu'],
          c: 3,
          w: 'Masa startowa (masa w locie) to suma wszystkiego, co unosi skrzydło: pilot, ubranie, uprząż, sprzęt i sama paralotnia.',
        },
        {
          q: 'Uprząż paralotniowa powinna posiadać:',
          o: ['regulację taśm', 'protektor', 'miejsce na zamocowanie SIP', 'wszystkie odpowiedzi są prawidłowe'],
          c: 3,
          w: 'Regulacja, ochrona pleców i kontener na spadochron ratunkowy to standardowe wyposażenie uprzęży.',
        },
      ],
    },
  ],
};
